apiVersion: v1
kind: Service
metadata:
  name: camunda
  labels:
    app: camunda
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    #nodePort: 30029
  selector:
    app: camunda
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  labels:
    app: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
      - name: camunda
        image: camunda/camunda-bpm-platform
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

